### ISSUE TITLE
Setup a MySQL database server.

### ISSUE THREAD

**Issue by krichardson864** [JarvisCapstone/Syllahub#4]
We need to set up a server we can use for our project.

**Comment by SShahabb** [comment]
Migrations, ORM, what else?

**Comment by SShahabb** [comment]
Looks like azure better than pythonanywhere for our purposes

**Comment by SShahabb** [comment]
Samba suggested that we use the kent server resources, and then we use azure for back up, testing, recovery, etc if we want.
